using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using HalconDotNet;
using System.Threading;

namespace develop_calibrate_camera
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        public HObject ho_Image = null, ho_GrayImage = null, ho_Regions = null;
        public HObject ho_ConnectedRegions = null, ho_SelectedRegions = null;
        public HTuple hv_AcqHandle = null;
        Thread dispig;
        public int chuli;
      
        public void getin()
        {
            HOperatorSet.GenEmptyObj(out ho_Image);
            HOperatorSet.GenEmptyObj(out ho_GrayImage);
            HOperatorSet.GenEmptyObj(out ho_Regions);
            HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
            HOperatorSet.GenEmptyObj(out ho_SelectedRegions);
            //Image Acquisition 01: Code generated by Image Acquisition 01
            HOperatorSet.OpenFramegrabber("DirectShow", 1, 1, 0, 0, 0, 0, "default", 8, "rgb",
        -1, "false", "default", "[0] Integrated Camera", 0, -1, out hv_AcqHandle);
            HOperatorSet.GrabImageStart(hv_AcqHandle, -1);
            while (true)
            {

                HOperatorSet.GrabImageAsync(out ho_Image, hv_AcqHandle, -1);
                HOperatorSet.DispObj(ho_Image, hWindowControl1.HalconWindow);

                if (chuli==1)
                {
                    chuli = 0;
                    HOperatorSet.DispObj(ho_Image, hWindowControl2.HalconWindow);
                    ho_GrayImage.Dispose();
                    HOperatorSet.Rgb1ToGray(ho_Image, out ho_GrayImage);
                    ho_Regions.Dispose();
                    HOperatorSet.Threshold(ho_GrayImage, out ho_Regions, 0, 129);
                    ho_ConnectedRegions.Dispose();
                    HOperatorSet.Connection(ho_Regions, out ho_ConnectedRegions);
                    ho_SelectedRegions.Dispose();
                    HOperatorSet.SelectShape(ho_ConnectedRegions, out ho_SelectedRegions, "area",
                        "and", 20000, 9999999);
                    HOperatorSet.DispObj(ho_SelectedRegions, hWindowControl2.HalconWindow);
                }               
                ho_GrayImage.Dispose();
                ho_Regions.Dispose();
                ho_ConnectedRegions.Dispose();
                ho_SelectedRegions.Dispose();
                ho_Image.Dispose();
            }
        }

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            if (dispig != null)
            {                
                dispig.Abort(); //结束这个线程
            }
        }
  
        private void button1_Click(object sender, EventArgs e)
        {
            dispig = new Thread(getin);
            dispig.Start();
        }

        private void button2_Click(object sender, EventArgs e)
        {
            chuli = 1;
        }

        private void button3_Click(object sender, EventArgs e)
        {
            ho_Image.Dispose();
            dispig.Abort();
            HOperatorSet.CloseAllFramegrabbers();
            //this.Close();
        }

        private void GetRegion( )
        {
            try 
            {
                
            }
            catch
            {

            }
        }
    }
}
