//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace MyNet.Atmcs.Uscmcp.Web.LogService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BigDataLogServiceHttpBinding", Namespace="http://interfaces.webservice.log.tvcc.zklt.com")]
    public partial class BigDataLogService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BigdataCollectionLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback BigdataSearchLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback MysqlErrorLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback MysqlCollectionLogOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BigDataLogService() {
            this.Url = global::MyNet.Atmcs.Uscmcp.Web.Properties.Settings.Default.MyNet_Atmcs_Uscmcp_Web_LogService_BigDataLogService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BigdataCollectionLogCompletedEventHandler BigdataCollectionLogCompleted;
        
        /// <remarks/>
        public event BigdataSearchLogCompletedEventHandler BigdataSearchLogCompleted;
        
        /// <remarks/>
        public event MysqlErrorLogCompletedEventHandler MysqlErrorLogCompleted;
        
        /// <remarks/>
        public event MysqlCollectionLogCompletedEventHandler MysqlCollectionLogCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://interfaces.webservice.log.tvcc.zklt.com", ResponseNamespace="http://interfaces.webservice.log.tvcc.zklt.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string BigdataCollectionLog([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("BigdataCollectionLog", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BigdataCollectionLogAsync(string in0) {
            this.BigdataCollectionLogAsync(in0, null);
        }
        
        /// <remarks/>
        public void BigdataCollectionLogAsync(string in0, object userState) {
            if ((this.BigdataCollectionLogOperationCompleted == null)) {
                this.BigdataCollectionLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBigdataCollectionLogOperationCompleted);
            }
            this.InvokeAsync("BigdataCollectionLog", new object[] {
                        in0}, this.BigdataCollectionLogOperationCompleted, userState);
        }
        
        private void OnBigdataCollectionLogOperationCompleted(object arg) {
            if ((this.BigdataCollectionLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BigdataCollectionLogCompleted(this, new BigdataCollectionLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://interfaces.webservice.log.tvcc.zklt.com", ResponseNamespace="http://interfaces.webservice.log.tvcc.zklt.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string BigdataSearchLog([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("BigdataSearchLog", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BigdataSearchLogAsync(string in0) {
            this.BigdataSearchLogAsync(in0, null);
        }
        
        /// <remarks/>
        public void BigdataSearchLogAsync(string in0, object userState) {
            if ((this.BigdataSearchLogOperationCompleted == null)) {
                this.BigdataSearchLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBigdataSearchLogOperationCompleted);
            }
            this.InvokeAsync("BigdataSearchLog", new object[] {
                        in0}, this.BigdataSearchLogOperationCompleted, userState);
        }
        
        private void OnBigdataSearchLogOperationCompleted(object arg) {
            if ((this.BigdataSearchLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BigdataSearchLogCompleted(this, new BigdataSearchLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://interfaces.webservice.log.tvcc.zklt.com", ResponseNamespace="http://interfaces.webservice.log.tvcc.zklt.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string MysqlErrorLog([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("MysqlErrorLog", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MysqlErrorLogAsync(string in0) {
            this.MysqlErrorLogAsync(in0, null);
        }
        
        /// <remarks/>
        public void MysqlErrorLogAsync(string in0, object userState) {
            if ((this.MysqlErrorLogOperationCompleted == null)) {
                this.MysqlErrorLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMysqlErrorLogOperationCompleted);
            }
            this.InvokeAsync("MysqlErrorLog", new object[] {
                        in0}, this.MysqlErrorLogOperationCompleted, userState);
        }
        
        private void OnMysqlErrorLogOperationCompleted(object arg) {
            if ((this.MysqlErrorLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MysqlErrorLogCompleted(this, new MysqlErrorLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://interfaces.webservice.log.tvcc.zklt.com", ResponseNamespace="http://interfaces.webservice.log.tvcc.zklt.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string MysqlCollectionLog([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("MysqlCollectionLog", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MysqlCollectionLogAsync(string in0) {
            this.MysqlCollectionLogAsync(in0, null);
        }
        
        /// <remarks/>
        public void MysqlCollectionLogAsync(string in0, object userState) {
            if ((this.MysqlCollectionLogOperationCompleted == null)) {
                this.MysqlCollectionLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMysqlCollectionLogOperationCompleted);
            }
            this.InvokeAsync("MysqlCollectionLog", new object[] {
                        in0}, this.MysqlCollectionLogOperationCompleted, userState);
        }
        
        private void OnMysqlCollectionLogOperationCompleted(object arg) {
            if ((this.MysqlCollectionLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MysqlCollectionLogCompleted(this, new MysqlCollectionLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    public delegate void BigdataCollectionLogCompletedEventHandler(object sender, BigdataCollectionLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BigdataCollectionLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BigdataCollectionLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    public delegate void BigdataSearchLogCompletedEventHandler(object sender, BigdataSearchLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BigdataSearchLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BigdataSearchLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    public delegate void MysqlErrorLogCompletedEventHandler(object sender, MysqlErrorLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MysqlErrorLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MysqlErrorLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    public delegate void MysqlCollectionLogCompletedEventHandler(object sender, MysqlCollectionLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.2012.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MysqlCollectionLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MysqlCollectionLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591