//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Atmcs.Uscmcp.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.2.111.71:8080/query_webservice/services/querypasscar")]
        public string MyNet_Atmcs_Uscmcp_Web_QueryService_querypasscar {
            get {
                return ((string)(this["MyNet_Atmcs_Uscmcp_Web_QueryService_querypasscar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.2.111.133:8080/other-webservice/services/OtherQueryInfo")]
        public string MyNet_Atmcs_Uscmcp_Web_OtherQueryService_OtherQueryInfo {
            get {
                return ((string)(this["MyNet_Atmcs_Uscmcp_Web_OtherQueryService_OtherQueryInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.2.111.249:8080/logs-webservice/services/BigDataLogService")]
        public string MyNet_Atmcs_Uscmcp_Web_LogService_BigDataLogService {
            get {
                return ((string)(this["MyNet_Atmcs_Uscmcp_Web_LogService_BigDataLogService"]));
            }
        }
    }
}
