/*************************************************************************************
		* CLR版本 ：       4.0.30319.42000
		* 类 名 称：       Hcamera
		* 机器名称：       AFOHC-608062000
		* 命名空间：       develop_calibrate_camera.Initialization_camera
		* 文 件 名：       Hcamera
		* 创建时间：       2017/8/11 12:51:35
		* 作    者：       mao
		* 说    明：
		* 修改时间：
		* 修 改 人：
*************************************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HalconDotNet;

namespace develop_calibrate_camera.Initialization_camera
{
    class Hcamera
    {
        public void getin()
        {
            HOperatorSet.GenEmptyObj(out ho_Image);
            HOperatorSet.GenEmptyObj(out ho_GrayImage);
            HOperatorSet.GenEmptyObj(out ho_Regions);
            HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
            HOperatorSet.GenEmptyObj(out ho_SelectedRegions);
            //Image Acquisition 01: Code generated by Image Acquisition 01
            HOperatorSet.OpenFramegrabber("DirectShow", 1, 1, 0, 0, 0, 0, "default", 8, "rgb",
        -1, "false", "default", "[0] Integrated Camera", 0, -1, out hv_AcqHandle);
            HOperatorSet.GrabImageStart(hv_AcqHandle, -1);
            while ((int)(1) != 0)
            {

                HOperatorSet.GrabImageAsync(out ho_Image, hv_AcqHandle, -1);
                HOperatorSet.DispObj(ho_Image, hSmartWindowControl1.HalconWindow);

                //Image Acquisition 01: Do something
                if (ChuLi == 1)
                {
                    ChuLi = 0;
                    HOperatorSet.DispObj(ho_Image, hSmartWindowControl2.HalconWindow);
                    ho_GrayImage.Dispose();
                    HOperatorSet.Rgb1ToGray(ho_Image, out ho_GrayImage);
                    ho_Regions.Dispose();
                    HOperatorSet.Threshold(ho_GrayImage, out ho_Regions, 0, 129);
                    ho_ConnectedRegions.Dispose();
                    HOperatorSet.Connection(ho_Regions, out ho_ConnectedRegions);
                    ho_SelectedRegions.Dispose();
                    HOperatorSet.SelectShape(ho_ConnectedRegions, out ho_SelectedRegions, "area",
                        "and", 11100.9, 15064.2);
                    HOperatorSet.DispObj(ho_SelectedRegions, hSmartWindowControl2.HalconWindow);
                }
                ho_Image.Dispose();
                ho_GrayImage.Dispose();
                ho_Regions.Dispose();
                ho_ConnectedRegions.Dispose();
                ho_SelectedRegions.Dispose();
            }
        }
    }
}
