document.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"http://10.2.111.144:99/BMaps/css/DrawingManager_min.css\" />");
document.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"http://10.2.111.144:99/BMaps/bmap.css\" />");
document.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"http://10.2.111.144:99/BMaps/css/SearchInfoWindow_min.css\" />");
document.write("  <script type=\"text/javascript\" src=\"http://10.2.111.144:99/BMaps/api/mapconfig.js\"></script>");
document.write(" <script type=\"text/javascript\" src=\"http://10.2.111.144:99/BMaps/api/mapapi.min.js\"></script>");
document.write(" <script type=\"text/javascript\" src=\"http://10.2.111.144:99/BMaps/lib/Drawingmanager.js\"></script>");
document.write(" <script type=\"text/javascript\" src=\"http://10.2.111.144:99/BMaps/lib/geoutils.min.js\"></script>");
document.write(" <script type=\"text/javascript\" src=\"http://10.2.111.144:99/BMaps/lib/DistanceTool.js\"></script>");
document.write(" <script type=\"text/javascript\" src=\"http://10.2.111.144:99/BMaps/lib/MarkerClusterer_min.js\"></script>");
document.write(" <script type=\"text/javascript\" src=\"http://10.2.111.144:99/BMaps/lib/TextIconOverlay_min.js\"></script>");
document.write(" <script type=\"text/javascript\" src=\"http://10.2.111.144:99/BMaps/lib/SearchInfoWindow_min.js\"></script>");
